### ISSUE TITLE
Can't unregister

### ISSUE THREAD

**Issue by 3317** [gigantessbeta/MoneyPlus--Peripheral-Plugin#2]
/mjob unregisterを実行した所以下のエラーが発生しました。

[CRITICAL] Unhandled exception executing command 'mjob unregister' in mjob: Undefined offset: 1
[CRITICAL] ErrorException: "Undefined offset: 1" (EXCEPTION) in "/plugins/MoneyPlusJob_v0.0.1.phar/src/GE/moneyplusjob/MoneyPlusJob" at line 113

**Comment by MyDeacy** [comment]
ご報告ありがとうございます。
修正しました。
[https://github.com/gigantessbeta/MoneyPlus-Peripheral-Plugins/commit/09cad6a62e98bbc64616bda147a1f23fd5042af5](https://github.com/gigantessbeta/MoneyPlus-Peripheral-Plugins/commit/09cad6a62e98bbc64616bda147a1f23fd5042af5)
